### PR TITLE
Slight clarification on adding Solarized and configuration to iTerm2 …

### PR DESCRIPTION
**Pull request by simplycycling**
…and Vim

Hi Jess - I ran into a bit of confusion when adding Solarized to iTerm2 and Vim, while following your excellent guide, so just added a couple notes in the README that would have made it a little easier on me.

Btw - thanks so much for putting this together. This is the first Mac I've ever owned, and coming from a Linux background, it felt similar to what I was used to (I'm talking mainly about living in the terminal), but just different enough to be annoying. Your setup makes it feel a lot more like home.

No worries if you don't think this adds any value.

### CODE REVIEW

**Comment by jessfraz** [comment]
awesome i donnt have a mac anymore to make sure this is up to date so thank you!

**Comment by matthewtrask** [comment]
Hey Jessie, since you don't have a mac anymore, are you still looking to maintain this or do you want someone to take over?

**Comment by jessfraz** [comment]
If you want to take it over that would be great!

On Fri, Jul 17, 2015 at 9:00 AM, Matt Trask notifications@github.com
wrote:

> Hey Jessie, since you don't have a mac anymore, are you still looking to
> maintain this or do you want someone to take over?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jfrazelle/mac-dev-setup/pull/4#issuecomment-122326475
> .

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by matthewtrask** [comment]
I think it would be awesome, definitely!

**Comment by jessfraz** [comment]
added as a collaborator!

**Comment by matthewtrask** [comment]
Sweet!

**Pull request merged**
